---
- name: build image and push to docker hub play
  hosts: ansible_host
  tasks:
  - name: remove image
    command: docker rmi saria2020/java-hello-world
    ignore_errors: true
  - name: build image
    command: docker build -t saria2020/java-hello-world ~/hello-world
#  - name: docker login
#    command: docker login -u saria2020 -p 
  - name: push image
    command: docker push saria2020/java-hello-world:latest
